export type Citation = { n: number; chunkId: string; materialId: string; materialTitle: string; subjectCode: string; profName: string; page: number }
export type Message = { id: string; role: 'user'|'assistant'; kind: 'user'|'answer'|'not_covered'|'clarify'; text: string; citations?: Citation[]; clarify?: { question: string; options: { subjectId: string; label: string; preview: string }[] }; chosenSubjectId?: string }
export type Conversation = { id: string; title: string; updatedAt: string; scope?: { profId?: string; subjectId?: string } }
export type Material = { id: string; subjectId: string; title: string; fileName: string; pageCount?: number; chunkCount?: number; status: 'uploaded'|'processing'|'ready'|'failed'; error?: string; term: string; createdAt: string }
// 'quiz' is multiple choice. 'identification' expects the typed `answer`; 'enumeration' expects every entry of `answers`, in any order.
export type StudyItem = { id: string; type: 'note'|'flashcard'|'quiz'|'identification'|'enumeration'; heading?: string; body?: string; front?: string; back?: string; prompt?: string; options?: string[]; answerIndex?: number; answer?: string; answers?: string[]; explanation?: string; citations?: Citation[] }
export type CoverageTopic = { topicId: string; title: string; matchedChunks: number; level: 'none'|'thin'|'good' }
export type Subject = { id: string; code: string; title: string; professor: string; profId: string }
export type StudySet = { id: string; title: string; subjectCode: string; items: StudyItem[]; due: number; studied: string }
export type User = { firstName: string; name: string; email?: string; program: string; role: 'Student'|'Professor'|'Admin' }
export type Role = User['role']
export type MockData = { subjects: Subject[]; conversations: Conversation[]; messages: Record<string, Message[]>; materials: Material[]; studySets: StudySet[]; coverage: Record<string, CoverageTopic[]>; user: User }

type SubjectSeed = [string,string,string,string]
const subjectSeeds: SubjectSeed[] = [['s1','CS 211','Data Science Fundamentals','Rodrigueza'],['s2','IT 213','Database Systems','Azares'],['s3','CS 314','Software Engineering','Mendoza'],['s4','CS 221','Algorithms','Dela Cruz'],['s5','CS 312','Machine Learning','Rodrigueza']]
export const subjects: Subject[] = subjectSeeds.map(([id,code,title,professor]) => ({ id, code, title, professor, profId: id+'p' }))
export const citations: Citation[] = [{ n: 1, chunkId:'c1', materialId:'m1', materialTitle:'Regression.pdf', subjectCode:'CS 211', profName:'Rodrigueza', page:4 }, { n: 2, chunkId:'c2', materialId:'m2', materialTitle:'Database Normalization.pdf', subjectCode:'IT 213', profName:'Azares', page:12 }]
export const materials: Material[] = [
 {id:'m1',subjectId:'s1',title:'Regression and Model Evaluation',fileName:'Regression.pdf',pageCount:18,chunkCount:42,status:'ready',term:'2nd Semester 2025–26',createdAt:'Sep 18, 2026'},
 {id:'m2',subjectId:'s2',title:'Database Normalization',fileName:'Database Normalization.pdf',pageCount:24,chunkCount:61,status:'ready',term:'2nd Semester 2025–26',createdAt:'Sep 15, 2026'},
 {id:'m3',subjectId:'s3',title:'Agile Software Development',fileName:'Agile Software Development.pdf',pageCount:31,chunkCount:80,status:'processing',term:'2nd Semester 2025–26',createdAt:'Sep 20, 2026'},
 {id:'m4',subjectId:'s4',title:'Graph Algorithms',fileName:'Graph Algorithms.pdf',pageCount:14,chunkCount:30,status:'uploaded',term:'2nd Semester 2025–26',createdAt:'Sep 21, 2026'},
 {id:'m5',subjectId:'s1',title:'Probability Review',fileName:'Probability Review.pdf',status:'failed',error:'No text found. This PDF may be scanned.',term:'2nd Semester 2025–26',createdAt:'Sep 10, 2026'},
 {id:'m6',subjectId:'s2',title:'SQL Query Patterns',fileName:'SQL Query Patterns.pdf',pageCount:16,chunkCount:37,status:'ready',term:'1st Semester 2025–26',createdAt:'Aug 28, 2026'}]
export const conversations: Conversation[] = [{id:'c1',title:'Bias-variance tradeoff',updatedAt:'Today'},{id:'c2',title:'Normalization in databases',updatedAt:'Today'},{id:'c3',title:'Agile principles',updatedAt:'Yesterday'},{id:'c4',title:'Graph traversal',updatedAt:'Previous 7 days'},{id:'c5',title:'Sorting complexity',updatedAt:'Previous 7 days'}]
export const messages: Record<string, Message[]> = { c1:[{id:'u1',role:'user',kind:'user',text:'Explain the bias-variance tradeoff'}, {id:'a1',role:'assistant',kind:'answer',text:'The **bias-variance tradeoff** is the balance between two kinds of error in a predictive model. *Bias* is the error from overly simple assumptions, while *variance* is the error from being too sensitive to the training data.\n\nA model with high bias underfits; a model with high variance overfits. The goal is to find a level of complexity that generalizes well to unseen data [1].',citations:[citations[0]]}], c2:[{id:'u2',role:'user',kind:'user',text:'What is normalization in databases?'},{id:'a2',role:'assistant',kind:'answer',text:'Normalization is the process of organizing data to reduce redundancy and improve data integrity. It typically involves splitting a table into related tables and defining relationships between them [2].',citations:[citations[1]]}], c3:[{id:'u3',role:'user',kind:'user',text:'What is an interface?'},{id:'a3',role:'assistant',kind:'clarify',text:'',clarify:{question:'This is taught differently in your subjects',options:[{subjectId:'s1',label:'CS 211 · Rodrigueza',preview:'defines it using matrix notation'},{subjectId:'s3',label:'CS 314 · Mendoza',preview:'frames it as a contract between modules'}]}}], c4:[{id:'u4',role:'user',kind:'user',text:'Explain blockchain consensus'},{id:'a4',role:'assistant',kind:'not_covered',text:''}]}
export const studySets: StudySet[] = [{id:'set1',title:'Midterm Review',subjectCode:'CS 211',due:8,studied:'Yesterday',items:[{id:'i1',type:'flashcard',front:'What is overfitting?',back:'When a model learns training data too closely and fails to generalize.',citations:[citations[0]]},{id:'i2',type:'note',heading:'Model evaluation',body:'Use a held-out validation set to estimate generalization error.',citations:[citations[0]]}]},{id:'set2',title:'Database Essentials',subjectCode:'IT 213',due:3,studied:'Sep 19, 2026',items:[{id:'i3',type:'quiz',prompt:'What does 1NF require?',options:['Atomic values','Foreign keys','Indexes','Views'],answerIndex:0,explanation:'First normal form requires each field to contain atomic values.',citations:[citations[1]]}]}]
export const coverage: Record<string,CoverageTopic[]> = {s1:[['t1','Linear regression',12,'good'],['t2','Probability',3,'thin'],['t3','Hypothesis testing',0,'none'],['t4','Classification',0,'none']].map(([topicId,title,matchedChunks,level])=>({topicId:title as string,title:title as string,matchedChunks:matchedChunks as number,level:level as 'good'|'thin'|'none'}))}
export const user: User = {firstName:'Peter',name:'Peter Poloan',email:'peter.poloan@example.edu',program:'BSCS 4-1',role:'Student'}
export const mockData: MockData = {subjects,conversations,messages,materials,studySets,coverage,user}
